# Generated by Django 2.0.5 on 2018-06-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='owner',
            new_name='username',
        ),
    ]
