# Generated by Django 2.0.6 on 2018-06-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180616_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='owner',
        ),
    ]
