# Generated by Django 2.0.5 on 2018-06-19 01:55

import api.services
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180619_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.BigIntegerField(default=api.services.LendingService.random_number, editable=False),
        ),
    ]
