# Generated by Django 2.0.5 on 2018-06-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
