# Generated by Django 2.0.5 on 2018-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180614_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='credit_line',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
