# Generated by Django 2.0.6 on 2018-06-15 07:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180615_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='apr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=2),
        ),
    ]
