# Generated by Django 2.0.5 on 2018-06-17 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20180616_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
