# Generated by Django 2.0.5 on 2018-06-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180614_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='balance',
            new_name='principal_balance',
        ),
    ]
